language: python
python: 3.7
os:
  - linux
  - osx
  - windows
install:
  - pip3 install --upgrade pip
  - pip install pandas sphinx
script: python3 platform-info.py

script:
  - |
    python3 -m sphinx -E -W -b=doctest "docs/source" "docs/_build"
