language: bash

python: 3.7

os:
  - linux
  - osx
  - windows

install:
  - |
    pip3 install --upgrade pip
    pip3 install pandas sphinx

script:
  - |
    python3 platform-info.py
    cd docs
    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
        MAKE=".\make.bat"
    else
        MAKE=make
    fi
    $MAKE doctest && python3 -m sphinx -E -W "source" "_build"
